#!/usr/bin/env bash
# Regenerates firmware/s3/main/fonts_cyrillic.c from u8g2's own BDFs, with u8g2's own converter.
# Never hand-edit the output.
#
# The glyph range is ASCII plus the Cyrillic block: 32-127 and 1024-1279 (U+0400..U+04FF). The
# full catalogue is deliberately not vendored -- see firmware/s3/components/u8g2/README.md.
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
OUT="$ROOT/firmware/s3/main/fonts_cyrillic.c"
WORK="$(mktemp -d)"
trap 'rm -rf "$WORK"' EXIT

# bdfconv and the BDFs come from upstream, not from the vendored copy: the vendored tree is
# csrc only, and trimmed. Pin the same commit the component README records.
UPSTREAM="https://github.com/olikraus/u8g2.git"
COMMIT="$(sed -n 's/^Upstream commit: //p' "$ROOT/firmware/s3/components/u8g2/README.md")"
git clone --quiet "$UPSTREAM" "$WORK/u8g2"
git -C "$WORK/u8g2" checkout --quiet "$COMMIT"

# Upstream's Makefile hardcodes CFLAGS="-O4 ...", and newer clang (Apple's, on a build host
# without gcc proper) treats -O4 as a deprecated alias for -O3 and fails under the Makefile's
# own -Werror. Override CFLAGS on the command line rather than edit the checkout: bdfconv is a
# throwaway host tool built fresh into $WORK each run, not part of the vendored component.
make -C "$WORK/u8g2/tools/font/bdfconv" CFLAGS="-O3 -Wall -Werror" >/dev/null

{
  echo '/* GENERATED by tools/gen_dongle_fonts.sh -- do not edit. */'
  echo '#include "u8g2.h"'
  for f in 10x20 9x15 6x12; do
    "$WORK/u8g2/tools/font/bdfconv/bdfconv" -f 1 -m '32-127,1024-1279' \
        -n "u8g2_font_${f}_t_cyrillic" -o "$WORK/part_${f}.c" \
        "$WORK/u8g2/tools/font/bdf/${f}.bdf" >/dev/null
    cat "$WORK/part_${f}.c"
  done
} > "$OUT"

echo "wrote $OUT ($(wc -c < "$OUT") bytes)"
